config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'dashboard#index'

  resources :dashboard, only: :index
  get :exercise_one, to: 'exercise_one#show'
  post :exercise_one, to: 'exercise_one#create'

  get :exercise_two, to: 'exercise_two#show'
  post :exercise_two, to: 'exercise_two#create'
  
  get :exercise_three, to: 'exercise_three#show'
  post :exercise_three, to: 'exercise_three#create'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/exercise_one_controller.rb
class ExerciseOneController < ApplicationController
  @@solution = []

  def show
    @solution = @@solution
  end

  def create
    @@solution = ExerciseOneService.new.call(params[:input_file])
    redirect_to :exercise_one
  end
end

app/controllers/exercise_three_controller.rb
class ExerciseThreeController < ApplicationController
  @@solution = []

  def show
    @solution = @@solution
  end

  def create
    @@solution = ExerciseThreeService.new.call(params[:input_file])
    redirect_to :exercise_three
  end
end

app/controllers/exercise_two_controller.rb
class ExerciseTwoController < ApplicationController
  @@solution = []

  def show
    @solution = @@solution
  end

  def create
    @@solution = ExerciseTwoService.new.call(params[:input_file])
    redirect_to :exercise_two
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def get_problem1_answer(x)
    end_of_line = x[:parked] ? "se parqueó en la posición #{x[:position]}" : "no se parqueó"
    str = "El auto de posición inicial #{x[:init]} " + end_of_line
  end
end

app/views/dashboard/index.html.erb
<div class="row">
  <h1>Prueba GC</h1>
</div>

<div class="row">
  <div class="col">
    <%= link_to 'Ejercicio 1', exercise_one_path, class: 'btn btn-primary btn-lg' %>
  </div>
  <div class="col">
    <%= link_to 'Ejercicio 2', exercise_two_path, class: 'btn btn-success btn-lg' %>
  </div>
  <div class="col">
    <%= link_to 'Ejercicio 3', exercise_three_path, class: 'btn btn-info btn-lg' %>
  </div>
</div>

app/views/exercise_one/show.html.erb
<h3>Carga Archivo para Resolver el ejercicio No. 1</h3>

<%= form_with url: exercise_one_path, local: true do |f| %>
  <div class="row">
    <div class="col-4">
      <div class="form-group">
        <%= f.label :input_file, 'Elige el archivo con el input de prueba' %>
        <%= f.file_field :input_file, class: 'form-control' %>
      </div>
    </div>
  </div>

  <div class="form-group mt-20">
    <%= f.submit 'Cargar', class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>

<hr>
<h5>Solución</h5>
<hr>

  <% @solution.each_with_index do |set, index| %>
  	<h5><%= "Conjunto de datos No. #{index+1}"%><h5>
		<% set.each do |x|%>
			<p><%=get_problem1_answer(x)%></p>
		<% end%>
  <% end%>

app/views/exercise_three/show.html.erb
<h3>Carga Archivo para Resolver el ejercicio No. 3</h3>

<%= form_with url: exercise_three_path, local: true do |f| %>
  <div class="row">
    <div class="col-4">
      <div class="form-group">
        <%= f.label :input_file, 'Elige el archivo con el input de prueba' %>
        <%= f.file_field :input_file, class: 'form-control' %>
      </div>
    </div>
  </div>

  <div class="form-group mt-20">
    <%= f.submit 'Cargar', class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>

<hr>
<h5>Solución</h5>
  <% @solution.each do |sol| %>
	<p><%= sol%></p>
  <% end%>

app/views/exercise_two/show.html.erb
<h3>Carga Archivo para Resolver el ejercicio No. 2</h3>

<%= form_with url: exercise_two_path, local: true do |f| %>
  <div class="row">
    <div class="col-4">
      <div class="form-group">
        <%= f.label :input_file, 'Elige el archivo con el input de prueba' %>
        <%= f.file_field :input_file, class: 'form-control' %>
      </div>
    </div>
  </div>

  <div class="form-group mt-20">
    <%= f.submit 'Cargar', class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>

<hr>
<h5>Solución</h5>
  <% @solution.each do |sol| %>
	<p><%= sol%></p>
  <% end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestGc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  </head>

  <body>
	  <%= render 'shared/header'%>
    <div class="container">
      <%= yield %>  
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to "Home", root_path, class: "navbar-brand"%>
</nav>